### PR TITLE
fix: Fixed recipe pricing

### PR DESCRIPTION
**Pull request by Teles1**
I'm not exactly sure how this packet was formed before but i couldn't get it to work... Objects doesn't seen to exist. I changed the code a bit to make it look for a regex pattern.

### CODE REVIEW

**Review by JustNao — CHANGES_REQUESTED** [review]
I'm using the `ChatClientMultiWithObjectMessage` packet, which is pretty self-explanatory. It should have an `objects` attribute for those linked objets. Can you show the debug window with the relevant packet ? Mine looks like this :
image
If it still is different, I would rather you keep the old method as a first option ; if the `objects` attribute isn't present, fall back to a regex on the content.

As for the server option, we could keep it in a config. We may merge `config/biscuit.json` with `config/multicompte.json` to have a global config file as a first step. We can add something in the UI later on. We could also pick it up from packets, some of them provide the server we're on. I would need to look for a reliable packet that gets sent often.

**Comment by Teles1** [comment]
That's interesting. I didn't do anything special besides invite another character of mine to my party and sending the recipe in the chat with the prefix "$price " the packet I got does not have objects in it... What's the procedure you used to trigger the server to send that packet specifically? Regarding the config, yep sounds good!

**Comment by JustNao** [comment]
Ah I see. The function is meant to work with **object** links, not **recipes**. I didn't even check to see how the command interacted with recipes ; you're absolutely right and they are just converted as text.
In that case my suggestion is still valid to make it work in both cases : I think we should first check for an `objects` attribute, and if not found, use you regex.

**Comment by Teles1** [comment]
Weird that I also tried that and couldn't really get it to work either. What about binding different packets? I'll check once I'm home! Thanks 🙏

**Review by JustNao — APPROVED** [review]

**Pull request merged**
